In [19]:
import pandas as pd
import random
import numpy as np

In [10]:
golden_data=pd.read_csv("./datasets/Colcom2018CleanedScaled.csv",header=0,sep=';')

## resumen de los datos originales de malware

In [12]:
golden_data[data.type=='malicious'].describe()

,tcp_packets,dist_port_tcp,external_ips,vulume_bytes,udp_packets,source_app_packets,remote_app_packets,source_app_bytes,remote_app_bytes,dns_query_times
count,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000,3141.000000
mean,0.554860,2.253422,-0.045633,0.557717,0.010825,0.536008,0.863371,3.650236,0.548932,0.422079
std,3.220602,18.069049,0.710032,2.810299,0.351354,3.106805,5.399236,25.833662,2.762755,4.009438
min,-0.290698,0.000000,-0.666667,-0.312383,0.000000,-0.322222,-0.282353,-0.164688,-0.324081,-0.750000
25%,-0.290698,0.000000,-0.666667,-0.312383,0.000000,-0.300000,-0.258824,-0.151903,-0.310083,-0.500000
50%,-0.151163,0.000000,-0.333333,-0.186501,0.000000,-0.133333,-0.117647,-0.099953,-0.158541,-0.250000
75%,0.186047,0.000000,0.333333,0.233372,0.000000,0.177778,0.176471,0.147614,0.222010,0.250000
max,54.406977,898.000000,5.666667,64.528792,12.000000,52.122222,78.423529,387.818441,62.931684,86.250000

In [38]:
generated_data=pd.read_csv("./datasets/malicious_data_generated.csv",header=0,sep=',')

In [27]:
features=['A','B','C','D','F','G','H','I','j','k']

## resumen de los datos generados a partir de fuerza bruta

In [42]:
generated_data.columns=['tcp_packets','dist_port_tcp','external_ips','vulume_bytes','udp_packets','source_app_packets','remote_app_packets','source_app_bytes','remote_app_bytes','dns_query_times']

In [43]:
generated_data.describe()

,tcp_packets,dist_port_tcp,external_ips,vulume_bytes,udp_packets,source_app_packets,remote_app_packets,source_app_bytes,remote_app_bytes,dns_query_times
count,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000,498.000000
mean,-26.883534,-29.712851,-39.361446,-9.823293,-29.921687,18.785141,-23.447791,22.004016,-15.622490,55.907631
std,48.589465,49.687918,42.702022,55.541643,47.479784,54.777729,48.962786,49.958131,54.640236,32.658644
min,-100.000000,-100.000000,-100.000000,-100.000000,-100.000000,-100.000000,-100.000000,-100.000000,-100.000000,-95.000000
25%,-64.000000,-67.000000,-72.000000,-58.000000,-66.000000,-14.000000,-64.000000,0.250000,-62.000000,37.000000
50%,-35.000000,-37.000000,-43.500000,-14.000000,-33.000000,25.000000,-27.000000,23.500000,-22.000000,61.500000
75%,-0.250000,-8.000000,-16.250000,32.750000,-10.000000,64.750000,0.000000,62.000000,25.750000,81.000000
max,100.000000,100.000000,95.000000,100.000000,99.000000,100.000000,100.000000,100.000000,99.000000,100.000000